### ISSUE TITLE
Pre-commit hooks

### ISSUE THREAD

**Issue by coreymcg** [NAEPDEV/benchmark#11]
It would be great to run the tests, linting and build before a commit. This should help prevent bugs and regressions. Basically protecting the codebase from myself 😅.

[Husky](https://github.com/typicode/husky) seems like it could be a good fit. Using lerna to [run these checks in parallel](https://github.com/lerna/lerna/tree/master/commands/run) would help speed up the process.

Running the builds for storybook and the docs would be a bonus. However, it depends on how much time it would add to the process.

**Comment by jimmy-james** [comment]
@coreymcg I'll look into this
