### ISSUE TITLE
MultiSelect propagation error

### ISSUE THREAD

**Issue by coreymcg** [NAEPDEV/benchmark#7]
The current MultiSelect story is throwing a propagation error when selecting an option.

`TypeError: Cannot read property 'stopPropagation' of undefined.`

**Comment by jimmy-james** [comment]
This doesn't happen for me on Storybook - perhaps resolved?

**Comment by coreymcg** [comment]
This was fixed in 4e88e2a60563601c64cae482c2e2ed0c12a095f8. 

Thanks for looking into this!

Closing.
